# Install dependencies only when needed
FROM node:lts
WORKDIR /app

# If using npm with a `package-lock.json` comment out above and use below instead
COPY package.json package-lock.json ./

# The access token for the GitHub Package registry
ARG NODE_AUTH_TOKEN

# Setup registry credentials
RUN if [ ! -z "$NODE_AUTH_TOKEN" ]; then echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc; fi

# Install app dependencies
RUN npm ci

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "dev", "--", "-p", "$PORT"]
